# Generated by Django 4.2.2 on 2023-08-11 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdata', '0002_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
