# Generated by Django 4.2.2 on 2023-08-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
